ALTER TABLE teachers ADD COLUMN last_name VARCHAR(50) NOT NULL;
ALTER TABLE teachers ADD COLUMN first_name VARCHAR(50) NOT NULL;
ALTER TABLE teachers DROP COLUMN name;

ALTER TABLE students ADD COLUMN last_name VARCHAR(50) NOT NULL;
ALTER TABLE students ADD COLUMN first_name VARCHAR(50) NOT NULL;
ALTER TABLE students DROP COLUMN name;
